version: '3'

services:
  external:
    container_name: sudomakes
    image: sudomakes
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1000M

    ports:
      - 5173:5173
